/*
 * generated by Xtext 2.28.0
 */
package life.game.parser.antlr;

import life.game.parser.antlr.internal.InternalGameDSLParser;
import org.antlr.runtime.Token;
import org.antlr.runtime.TokenSource;
import org.eclipse.xtext.parser.antlr.AbstractIndentationTokenSource;

public class GameDSLTokenSource extends AbstractIndentationTokenSource {

	public GameDSLTokenSource(TokenSource delegate) {
		super(delegate);
	}

	@Override
	protected boolean shouldSplitTokenImpl(Token token) {
		// TODO Review assumption
		return token.getType() == InternalGameDSLParser.RULE_WS;
	}

	@Override
	protected int getBeginTokenType() {
		// TODO Review assumption
		return InternalGameDSLParser.RULE_BEGIN;
	}

	@Override
	protected int getEndTokenType() {
		// TODO Review assumption
		return InternalGameDSLParser.RULE_END;
	}

}
